services:
  api:
    # image: gin:1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=testdb
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
